#!/usr/bin/env Rscript
# ==============================================================================
# r/evaluate_model.R - MSSF Evaluation Visualisation (R Layer)
# ==============================================================================
# Reads Python evaluation output and produces publication-quality ggplot2 charts.
#
# Inputs  (generated by python/evaluate.py):
#   evaluation/metrics_summary.json          — all scalars + confusion matrix
#   evaluation/predictions_with_labels.csv   — per-row predictions
#
# Outputs (saved to evaluation/r_plots/ by default):
#   01_confusion_matrix.png     — styled heatmap with counts + row%
#   02_per_class_metrics.png    — grouped bar: Precision / Recall / F1 / AUC
#   03_confidence_correct.png   — confidence split by correct vs wrong
#   04_calibration.png          — reliability (calibration) diagram
#   05_error_analysis.png       — which true class gets confused where
#   06_label_distribution.png   — true vs predicted distribution
#   evaluation_report.txt       — human-readable text summary
#
# Usage:
#   Rscript r/evaluate_model.R
#   Rscript r/evaluate_model.R evaluation/metrics_summary.json \
#                               evaluation/predictions_with_labels.csv \
#                               evaluation/r_plots
# ==============================================================================

# ── Packages ──────────────────────────────────────────────────────────────────
required <- c("ggplot2", "dplyr", "tidyr", "scales", "jsonlite", "forcats", "patchwork")
for (pkg in required) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
        install.packages(pkg, repos = "https://cran.rstudio.com/", quiet = TRUE)
    }
    suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}

# ── Arguments ─────────────────────────────────────────────────────────────────
args       <- commandArgs(trailingOnly = TRUE)
json_path  <- ifelse(length(args) >= 1, args[1], "evaluation/metrics_summary.json")
csv_path   <- ifelse(length(args) >= 2, args[2], "evaluation/predictions_with_labels.csv")
output_dir <- ifelse(length(args) >= 3, args[3], "evaluation/r_plots")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

cat("==============================================================\n")
cat(" MSSF R Evaluation Layer\n")
cat("==============================================================\n")
cat(" JSON  :", json_path,  "\n")
cat(" CSV   :", csv_path,   "\n")
cat(" Output:", output_dir, "\n\n")

# ── Validate inputs ────────────────────────────────────────────────────────────
if (!file.exists(json_path)) {
    cat("ERROR: JSON not found:", json_path, "\n")
    cat("Run first:  python python/evaluate.py\n")
    quit(status = 1)
}
if (!file.exists(csv_path)) {
    cat("ERROR: CSV not found:", csv_path, "\n")
    quit(status = 1)
}

# ── Load data ──────────────────────────────────────────────────────────────────
meta   <- fromJSON(json_path)
df     <- read.csv(csv_path, stringsAsFactors = FALSE)

# Coerce correct column from character ("TRUE"/"FALSE") to logical
df$correct <- as.logical(df$correct)

# Normalise
df$true_label <- tolower(trimws(df$true_label))
df$pred_label <- tolower(trimws(df$pred_label))
VALID  <- c("positive", "neutral", "negative")
df     <- df[df$true_label %in% VALID & df$pred_label %in% VALID, ]

COLORS <- c(positive = "#22c55e", neutral = "#f59e0b", negative = "#ef4444")
THEME  <- theme_minimal(base_size = 13) +
    theme(
        plot.title      = element_text(face="bold", size=14, hjust=0),
        plot.subtitle   = element_text(color="gray40", size=11),
        axis.title      = element_text(face="bold"),
        panel.grid.minor = element_blank(),
        legend.position = "right"
    )

ggsave_ <- function(name, plot, w=9, h=6) {
    path <- file.path(output_dir, name)
    ggsave(path, plot = plot, width = w, height = h, dpi = 160, bg = "white")
    cat(sprintf("  Saved: %s\n", name))
}

# ==============================================================================
# Plot 1 — Confusion Matrix heatmap (with counts + row-normalised %)
# ==============================================================================
cat("Generating confusion matrix...\n")

cm_raw    <- meta$confusion_matrix
cm_labels <- cm_raw$labels
# fromJSON may return a native R matrix or a list depending on jsonlite version
cm_mat <- if (is.matrix(cm_raw$matrix)) {
    cm_raw$matrix
} else {
    as.matrix(do.call(rbind, lapply(cm_raw$matrix, unlist)))
}

# Build long data frame
cm_df <- expand.grid(True = cm_labels, Predicted = cm_labels, stringsAsFactors = FALSE)
cm_df$Count <- as.vector(t(cm_mat))   # row = True, col = Predicted (R is column-major)

# Row-normalised percentage
cm_df <- cm_df |>
    group_by(True) |>
    mutate(
        RowTotal = sum(Count),
        Pct      = ifelse(RowTotal > 0, Count / RowTotal, 0),
        Label    = paste0(Count, "\n(", round(Pct*100, 1), "%)")
    ) |>
    ungroup()

cm_df$True      <- factor(cm_df$True,      levels = rev(cm_labels))
cm_df$Predicted <- factor(cm_df$Predicted, levels = cm_labels)

p1 <- ggplot(cm_df, aes(x = Predicted, y = True, fill = Pct)) +
    geom_tile(color = "white", linewidth = 0.8) +
    geom_text(aes(label = Label), size = 4.5, fontface = "bold",
              color = ifelse(cm_df$Pct > 0.5, "white", "gray20")) +
    scale_fill_gradient2(
        low = "white", mid = "#93c5fd", high = "#1d4ed8",
        midpoint = 0.5,
        labels   = percent_format(),
        name     = "Row %"
    ) +
    scale_x_discrete(position = "top", labels = tools::toTitleCase) +
    scale_y_discrete(labels = tools::toTitleCase) +
    labs(
        title    = "Confusion Matrix",
        subtitle = sprintf("n = %s | Accuracy = %.2f%%  |  Macro-F1 = %.4f",
                           format(meta$n_test, big.mark=","),
                           meta$accuracy * 100,
                           meta$macro_f1),
        x = "Predicted label",
        y = "True label"
    ) +
    THEME +
    theme(legend.position = "right",
          axis.text = element_text(face="bold", size=12))

ggsave_("01_confusion_matrix.png", p1, w=8, h=6)

# ==============================================================================
# Plot 2 — Per-class Precision / Recall / F1 / AUC
# ==============================================================================
cat("Generating per-class metrics bar chart...\n")

pc    <- meta$per_class
lbls  <- names(pc)

metrics_df <- do.call(rbind, lapply(lbls, function(lbl) {
    v <- pc[[lbl]]
    data.frame(
        Class     = lbl,
        Metric    = c("Precision", "Recall", "F1", "AUC"),
        Value     = c(v$precision, v$recall, v$f1,
                      ifelse(is.null(v$roc_auc), NA_real_, v$roc_auc)),
        stringsAsFactors = FALSE
    )
}))
metrics_df <- metrics_df[!is.na(metrics_df$Value), ]
metrics_df$Class  <- factor(metrics_df$Class,  levels = VALID)
metrics_df$Metric <- factor(metrics_df$Metric, levels = c("Precision","Recall","F1","AUC"))

p2 <- ggplot(metrics_df, aes(x = Class, y = Value, fill = Metric)) +
    geom_col(position = position_dodge(0.75), width = 0.7, color = NA) +
    geom_text(aes(label = sprintf("%.3f", Value)),
              position = position_dodge(0.75), vjust = -0.4, size = 3.5, fontface="bold") +
    scale_fill_manual(values = c(
        Precision = "#6366f1", Recall = "#f59e0b", F1 = "#22c55e", AUC = "#ec4899"
    )) +
    scale_y_continuous(labels = percent_format(), limits = c(0, 1.12), expand = c(0,0)) +
    scale_x_discrete(labels = tools::toTitleCase) +
    labs(
        title    = "Per-Class Performance Metrics",
        subtitle = sprintf("Accuracy: %.2f%%  | Macro-F1: %.4f  | Weighted-F1: %.4f",
                           meta$accuracy*100, meta$macro_f1, meta$weighted_f1),
        x = "Sentiment Class", y = "Score", fill = "Metric"
    ) +
    THEME

ggsave_("02_per_class_metrics.png", p2, w=10, h=6)

# ==============================================================================
# Plot 3 — Confidence: correct vs. wrong predictions
# ==============================================================================
cat("Generating confidence correctness plot...\n")

df$Result <- ifelse(df$correct, "Correct", "Incorrect")
df$Result <- factor(df$Result, levels = c("Correct","Incorrect"))

p3 <- ggplot(df, aes(x = confidence, fill = pred_label, alpha = Result)) +
    geom_histogram(bins = 40, color = "white", linewidth = 0.2,
                   position = "identity") +
    facet_wrap(~ pred_label, nrow = 1, labeller = labeller(pred_label = tools::toTitleCase)) +
    scale_fill_manual(values = COLORS, guide = "none") +
    scale_alpha_manual(values = c(Correct = 0.85, Incorrect = 0.40)) +
    scale_x_continuous(labels = percent_format()) +
    labs(
        title    = "Model Confidence — Correct vs. Incorrect Predictions",
        subtitle = "Transparent bars = wrong; solid bars = correct",
        x = "Confidence (max softmax)", y = "Count", alpha = "Result"
    ) +
    THEME +
    theme(legend.position = "bottom",
          strip.text = element_text(face="bold", size=12))

ggsave_("03_confidence_correct.png", p3, w=12, h=5)

# ==============================================================================
# Plot 4 — Reliability / Calibration diagram
# ==============================================================================
cat("Generating calibration diagram...\n")

calib_df <- df |>
    mutate(confidence_bin = cut(confidence, breaks = seq(0.3, 1, by = 0.07),
                                include.lowest = TRUE)) |>
    group_by(confidence_bin, pred_label) |>
    summarise(
        mean_conf = mean(confidence),
        accuracy  = mean(correct),
        n         = n(),
        .groups   = "drop"
    ) |>
    filter(!is.na(confidence_bin), n >= 5)

p4 <- ggplot(calib_df, aes(x = mean_conf, y = accuracy, color = pred_label, size = n)) +
    geom_abline(slope = 1, intercept = 0, lty = "dashed", color = "gray50", lwd = 1) +
    geom_point(alpha = 0.85) +
    geom_line(aes(group = pred_label), alpha = 0.6, linewidth = 1) +
    scale_color_manual(values = COLORS, labels = tools::toTitleCase, name = "Class") +
    scale_size_area(max_size = 12, name = "n samples") +
    scale_x_continuous(labels = percent_format(), limits = c(0.28, 1.02)) +
    scale_y_continuous(labels = percent_format(), limits = c(0, 1.02)) +
    labs(
        title    = "Reliability (Calibration) Diagram",
        subtitle = "Points on the diagonal = perfectly calibrated",
        x = "Mean predicted confidence (bin)", y = "Fraction correct"
    ) +
    THEME

ggsave_("04_calibration.png", p4, w=9, h=6)

# ==============================================================================
# Plot 5 — Error analysis: true class vs predicted class (heatmap without diagonal)
# ==============================================================================
cat("Generating error analysis heatmap...\n")

errors <- df[!df$correct, ] |>
    count(true_label, pred_label) |>
    mutate(
        true_label = factor(true_label, levels = VALID),
        pred_label = factor(pred_label, levels = VALID)
    )

p5 <- ggplot(errors, aes(x = pred_label, y = true_label, fill = n, label = n)) +
    geom_tile(color = "white", linewidth = 0.5) +
    geom_text(size = 5, fontface = "bold", color = "white") +
    scale_fill_gradientn(
        colours = c("#fef3c7","#f59e0b","#dc2626"),
        name    = "Error count"
    ) +
    scale_x_discrete(labels = tools::toTitleCase, position = "top") +
    scale_y_discrete(labels = tools::toTitleCase) +
    labs(
        title    = "Error Analysis — Misclassification Heatmap",
        subtitle = "Only incorrect predictions shown",
        x = "Predicted (wrong)", y = "True Label"
    ) +
    THEME

ggsave_("05_error_analysis.png", p5, w=7, h=5)

# ==============================================================================
# Plot 6 — True vs Predicted label distribution (side-by-side)
# ==============================================================================
cat("Generating label distribution comparison...\n")

true_counts <- df |> count(Class = true_label) |> mutate(Type = "True")
pred_counts <- df |> count(Class = pred_label) |> mutate(Type = "Predicted")
dist_df     <- bind_rows(true_counts, pred_counts) |>
    mutate(
        Class = factor(Class, levels = VALID),
        Type  = factor(Type, levels = c("True","Predicted"))
    )

p6 <- ggplot(dist_df, aes(x = Class, y = n, fill = Class, alpha = Type)) +
    geom_col(position = position_dodge(0.65), width = 0.6, color = "white") +
    geom_text(aes(label = format(n, big.mark=",")),
              position = position_dodge(0.65), vjust = -0.4, size = 3.5, fontface="bold") +
    scale_fill_manual(values = COLORS, guide = "none") +
    scale_alpha_manual(values = c(True = 1, Predicted = 0.55), name = "Distribution") +
    scale_x_discrete(labels = tools::toTitleCase) +
    scale_y_continuous(labels = label_comma(), expand = expansion(mult = c(0, 0.12))) +
    labs(
        title    = "True vs Predicted Label Distribution",
        subtitle = "Mismatch between bars indicates systematic bias",
        x = "Sentiment Class", y = "Count"
    ) +
    THEME +
    theme(legend.position = "bottom")

ggsave_("06_label_distribution.png", p6, w=9, h=6)

# ==============================================================================
# Text report
# ==============================================================================
cat("Writing text summary...\n")

report_lines <- c(
    "================================================================",
    " MSSF MODEL EVALUATION REPORT (R Layer)",
    "================================================================",
    sprintf(" Model mode       : %s", meta$model_mode),
    sprintf(" Test samples     : %s", format(meta$n_test, big.mark=",")),
    sprintf(" Accuracy         : %.4f  (%.2f%%)", meta$accuracy, meta$accuracy*100),
    sprintf(" Macro-F1         : %.4f", meta$macro_f1),
    sprintf(" Weighted-F1      : %.4f", meta$weighted_f1),
    "----------------------------------------------------------------",
    sprintf(" %-14s %10s %10s %8s %10s",
            "Class", "Precision", "Recall", "F1", "Support"),
    paste(rep("-", 56), collapse="")
)
for (lbl in names(meta$per_class)) {
    v <- meta$per_class[[lbl]]
    auc_str <- if (!is.null(v$roc_auc)) sprintf("  AUC=%.3f", v$roc_auc) else ""
    report_lines <- c(report_lines, sprintf(
        " %-14s %10.4f %10.4f %8.4f %10d%s",
        lbl, v$precision, v$recall, v$f1, v$support, auc_str
    ))
}
report_lines <- c(report_lines,
    "================================================================",
    " Confusion Matrix:",
    paste(c("", sprintf("%12s", meta$confusion_matrix$labels)), collapse="  ")
)
for (i in seq_along(meta$confusion_matrix$labels)) {
    row_vals <- meta$confusion_matrix$matrix[[i]]
    report_lines <- c(report_lines,
        paste(c(sprintf("%12s", meta$confusion_matrix$labels[i]),
                sprintf("%12d", row_vals)), collapse="  ")
    )
}
report_lines <- c(report_lines,
    "================================================================",
    sprintf(" Plots saved to: %s", normalizePath(output_dir, mustWork=FALSE))
)

report_path <- file.path(output_dir, "evaluation_report.txt")
writeLines(report_lines, report_path)
cat(sprintf("  Saved: evaluation_report.txt\n"))

# ── Print to console too ───────────────────────────────────────────────────────
cat("\n")
cat(paste(report_lines, collapse="\n"), "\n")
cat(sprintf("\n✓ R evaluation complete. All visuals in: %s\n\n", output_dir))
